### ISSUE TITLE
CONTRIBUTING.md references old info on the repo and conda environment

### ISSUE THREAD

**Issue by padamson** [USNavalResearchLaboratory/nepc#53]
# Tasks
- [x] reference repo location on GitHub
- [x] reference environment-dev.yml
- [x] update conda environments to use conda-forge
